name: Check Confluence Release Plan Link

on:
  pull_request:
    branches:
      - main

jobs:
  check-confluence-link:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Confluence Release Plan Link
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DESCRIPTION=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "${{ github.event.pull_request.url }}" | jq -r .body)

          # Check for a Confluence link in the PR description
          if [[ ! "$DESCRIPTION" =~ https://ajaib\.atlassian\.net/wiki/ ]]; then
            echo "::error ::A Confluence release plan link is missing in the PR description."
            exit 1  # Exit with an error status to fail the action
          fi

          echo "Confluence release plan link found in the PR description."