name: Check Confluence Release Plan Link

on:
  pull_request:
    branches:
      - stg

jobs:
  check-confluence-link:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Confluence Release Plan Link
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DESCRIPTION=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "${{ github.event.pull_request.url }}" | jq -r .body)

          # Get the current date in YYYY-MM-DD format
          CURRENT_DATE=$(date +'%Y-%m-%d')

          # Extract the link with the date from the PR description
          LINK=$(echo "$DESCRIPTION" | grep -o 'https://ajaib.atlassian.net/wiki/.+\[[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\]')

          if [[ -z "$LINK" ]]; then
            echo "A Confluence release plan link with the domain https://ajaib.atlassian.net/wiki/ is missing in the PR description."
            exit 1
          fi

          # Extract the date from the link
          LINK_DATE=$(echo "$LINK" | grep -o '[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}')

          # Check if the date matches the current date
          if [[ "$LINK_DATE" != "$CURRENT_DATE" ]]; then
            echo "The date in the Confluence link ($LINK_DATE) does not match the current date ($CURRENT_DATE)."
            exit 1
          fi

          echo "Confluence release plan link found and date matches the current date."