name: Check Confluence Release Plan Link

on:
  pull_request:
    branches:
      - main

jobs:
  check-confluence-link:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Confluence Release Plan Link
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch the PR description
          DESCRIPTION=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "${{ github.event.pull_request.url }}" | jq -r .body)

          # Print the PR description for debugging
          echo "PR Description: $DESCRIPTION"

          # Get the current date in YYYY-MM-DD format
          CURRENT_DATE=$(date +'%Y-%m-%d')
          echo "Current Date: $CURRENT_DATE"

          # Check for the presence of a Confluence link
          LINK=$(echo "$DESCRIPTION" | grep -o 'https://ajaib.atlassian.net/wiki/[^\"]*')
          
          # Debug output for the link
          if [[ -z "$LINK" ]]; then
            echo "::error::A Confluence release plan link with the domain https://ajaib.atlassian.net/wiki/ is missing in the PR description."
            exit 1  # Exit with an error status to fail the action
          else
            echo "Found Confluence Link: $LINK"
          fi

          # Extract the date from the link, assuming the date format is YYYY-MM-DD
          LINK_DATE=$(echo "$LINK" | grep -o '[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}')

          # Debug output for the extracted date
          if [[ -z "$LINK_DATE" ]]; then
            echo "::error::No valid date found in the Confluence link."
            exit 1
          fi
          echo "Date in Link: $LINK_DATE"

          # Check if the date in the link matches the current date
          if [[ "$LINK_DATE" != "$CURRENT_DATE" ]]; then
            echo "::error::The date in the Confluence link ($LINK_DATE) does not match the current date ($CURRENT_DATE)."
            exit 1
          fi

          echo "Confluence release plan link found, and date matches the current date."